x-healthcheck: &default-healthcheck
  interval: 5m
  timeout: 10s
  retries: 3
  start_period: 20s

services:
  syllogi-backend:
    container_name: syllogi-backend
    image: ghcr.io/jeraldlyh/syllogi/backend:latest
    environment:
      - TZ=Asia/Singapore
      - DATABASE_USERNAME=syllogi
      - DATABASE_PASSWORD=syllogi
      - DATABASE_NAME=syllogi
      - DATABASE_URL=syllogi-postgres:5432
      - YOUTUBE_DOWNLOAD_DIR=/downloads
      - DISABLE_MUSIC_VIDEO_DOWNLOADS=true
      - DISCORD_WEBHOOK_URL=
      - JELLYFIN_API_KEY=
      - JELLYFIN_BASE_URL=
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./downloads:/downloads
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8000/api/health || exit 1
    restart: unless-stopped

  syllogi-postgres:
    container_name: syllogi-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=syllogi
      - POSTGRES_DB=syllogi
      - POSTGRES_PASSWORD=syllogi
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      <<: *default-healthcheck
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
    restart: unless-stopped

  syllogi-web:
    container_name: syllogi-web
    image: ghcr.io/jeraldlyh/syllogi/web:latest
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    restart: unless-stopped
