x-healthcheck: &default-healthcheck
  interval: 5m
  timeout: 10s
  retries: 3
  start_period: 20s

services:
  syllogi:
    container_name: syllogi
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - TZ=Asia/Singapore
      - DATABASE_USERNAME=syllogi
      - DATABASE_PASSWORD=syllogi
      - DATABASE_NAME=syllogi
      - DATABASE_URL=syllogi-postgres:5432
      - YOUTUBE_DOWNLOAD_DIR=/downloads
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - ENVIRONMENT=development
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./backend:/app/backend:delegated
      - ./web:/app/web:delegated
      - web_node_modules:/app/web/node_modules
      - web_next:/app/web/.next
      - ./downloads:/downloads
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8000/api/health || exit 1
    restart: unless-stopped
    depends_on:
      syllogi-postgres:
        condition: service_healthy

  syllogi-postgres:
    container_name: syllogi-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=syllogi
      - POSTGRES_DB=syllogi
      - POSTGRES_PASSWORD=syllogi
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      <<: *default-healthcheck
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
    restart: unless-stopped

volumes:
  web_node_modules:
  web_next:
