"""add-enable-download-to-playlist

Revision ID: 07c0ac966e87
Revises: be27cd17b487
Create Date: 2026-03-31 11:51:22.890042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07c0ac966e87"
down_revision: Union[str, Sequence[str], None] = "be27cd17b487"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playlist",
        sa.Column(
            "enable_download",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlist", "enable_download")
    # ### end Alembic commands ###
