"""create_playlist_table

Revision ID: 160b7f57fb16
Revises: bfa06947f1f7
Create Date: 2026-02-28 18:50:33.745601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '160b7f57fb16'
down_revision: Union[str, Sequence[str], None] = 'bfa06947f1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('spotify', 'youtube', name='playlistprovider'), nullable=False),
    sa.Column('playlist_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('playlist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_playlist_id'), 'playlist', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_provider'), 'playlist', ['provider'], unique=False)
    op.create_index(op.f('ix_playlist_username'), 'playlist', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_username'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_provider'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_playlist_id'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
