"""create-recommendation-model

Revision ID: 429a26cd4a74
Revises: 4d9b252b3b9d
Create Date: 2026-04-19 20:08:09.802334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '429a26cd4a74'
down_revision: Union[str, Sequence[str], None] = '4d9b252b3b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendationsession',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider', sa.Enum('lastfm', name='recommendationprovider'), nullable=False),
    sa.Column('strategy', sa.Enum('top_tracks', 'recent_tracks', name='recommendationstrategy'), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='recommendationstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendationsession_provider'), 'recommendationsession', ['provider'], unique=False)
    op.create_index(op.f('ix_recommendationsession_username'), 'recommendationsession', ['username'], unique=False)
    op.create_table('recommendationsessiontrack',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('type', sa.Enum('matched', 'missing', 'downloaded', 'total', name='recommendationtracktype'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_session_id'], ['recommendationsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendationsessiontrack_recommendation_session_id'), 'recommendationsessiontrack', ['recommendation_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendationsessiontrack_recommendation_session_id'), table_name='recommendationsessiontrack')
    op.drop_table('recommendationsessiontrack')
    op.drop_index(op.f('ix_recommendationsession_username'), table_name='recommendationsession')
    op.drop_index(op.f('ix_recommendationsession_provider'), table_name='recommendationsession')
    op.drop_table('recommendationsession')
    op.execute('DROP TYPE IF EXISTS recommendationtracktype')
    op.execute('DROP TYPE IF EXISTS recommendationstatus')
    op.execute('DROP TYPE IF EXISTS recommendationstrategy')
    op.execute('DROP TYPE IF EXISTS recommendationprovider')
    # ### end Alembic commands ###
