"""add-oauthid-to-user

Revision ID: 4d9b252b3b9d
Revises: 81dbaf4c3f74
Create Date: 2026-04-12 16:14:07.784638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d9b252b3b9d'
down_revision: Union[str, Sequence[str], None] = '81dbaf4c3f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.create_index(op.f('ix_user_oauth_id'), 'user', ['oauth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user')
    op.drop_column('user', 'oauth_id')
    # ### end Alembic commands ###
