"""add-image-url-to-download-session

Revision ID: 4de9602bbcfa
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 14:43:35.599860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4de9602bbcfa'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloadsession', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloadsession', 'image_url')
    # ### end Alembic commands ###
