"""add-lastfm-username-to-musicserveruser

Revision ID: 5xuo84yj9j0h
Revises: 7bf06f897ad4
Create Date: 2026-06-19 15:48:06.214209

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5xuo84yj9j0h"
down_revision: str | Sequence[str] | None = "7bf06f897ad4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "musicserveruser",
        sa.Column(
            "lastfm_username",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            server_default="",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("musicserveruser", "lastfm_username")
    # ### end Alembic commands ###
