"""initial_migration

Revision ID: 701271051759
Revises: 
Create Date: 2026-02-20 19:00:51.046523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '701271051759'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('discord', name='notificationchannel'), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_table('syncsession',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('spotify', 'youtube', name='syncprovider'), nullable=False),
    sa.Column('provider_playlist_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider_playlist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('target_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_playlist_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_playlist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='syncstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncsession_provider'), 'syncsession', ['provider'], unique=False)
    op.create_index(op.f('ix_syncsession_provider_playlist_id'), 'syncsession', ['provider_playlist_id'], unique=False)
    op.create_index(op.f('ix_syncsession_target_playlist_id'), 'syncsession', ['target_playlist_id'], unique=False)
    op.create_index(op.f('ix_syncsession_target_user_id'), 'syncsession', ['target_user_id'], unique=False)
    op.create_table('syncsessiontrack',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sync_session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('total', 'new', 'outdated', 'missing', name='tracklistkind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.ForeignKeyConstraint(['sync_session_id'], ['syncsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncsessiontrack_kind'), 'syncsessiontrack', ['kind'], unique=False)
    op.create_index(op.f('ix_syncsessiontrack_sync_session_id'), 'syncsessiontrack', ['sync_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncsessiontrack_sync_session_id'), table_name='syncsessiontrack')
    op.drop_index(op.f('ix_syncsessiontrack_kind'), table_name='syncsessiontrack')
    op.drop_table('syncsessiontrack')
    op.drop_index(op.f('ix_syncsession_target_user_id'), table_name='syncsession')
    op.drop_index(op.f('ix_syncsession_target_playlist_id'), table_name='syncsession')
    op.drop_index(op.f('ix_syncsession_provider_playlist_id'), table_name='syncsession')
    op.drop_index(op.f('ix_syncsession_provider'), table_name='syncsession')
    op.drop_table('syncsession')
    op.drop_table('notification')
    # ### end Alembic commands ###
