"""create-recommendation-model

Revision ID: 7bed13ea712a
Revises: d09e406a2f04
Create Date: 2026-04-22 21:03:28.853893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7bed13ea712a"
down_revision: Union[str, Sequence[str], None] = "d09e406a2f04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    recommendation_strategy = postgresql.ENUM(
        "top_tracks",
        "recent_tracks",
        name="recommendationstrategy",
        create_type=False,
    )

    op.create_table(
        "recommendation",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("strategy", recommendation_strategy, nullable=False),
        sa.Column(
            "lastfm_username",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_username"), "recommendation", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendation_username"), table_name="recommendation")
    op.drop_table("recommendation")
    # ### end Alembic commands ###
