"""create-music-server-user-model

Revision ID: 7bf06f897ad4
Revises: 94a6b629597a
Create Date: 2026-06-18 21:44:00.178064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7bf06f897ad4'
down_revision: Union[str, Sequence[str], None] = '94a6b629597a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musicserveruser',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider', sa.Enum('jellyfin', 'navidrome', name='musicserverprovider'), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'provider', name='unique_musicserveruser_username_provider')
    )
    op.create_index(op.f('ix_musicserveruser_provider'), 'musicserveruser', ['provider'], unique=False)
    op.create_index(op.f('ix_musicserveruser_username'), 'musicserveruser', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musicserveruser_username'), table_name='musicserveruser')
    op.drop_index(op.f('ix_musicserveruser_provider'), table_name='musicserveruser')
    op.drop_table('musicserveruser')
    # ### end Alembic commands ###
