"""remove-unique-username-from-recommendation

Revision ID: 94a6b629597a
Revises: d1e943539d2e
Create Date: 2026-06-14 13:39:17.882286

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94a6b629597a"
down_revision: str | Sequence[str] | None = "d1e943539d2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendation_username"), table_name="recommendation")
    op.create_index(
        op.f("ix_recommendation_username"), "recommendation", ["username"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendation_username"), table_name="recommendation")
    op.create_index(
        op.f("ix_recommendation_username"), "recommendation", ["username"], unique=True
    )
    # ### end Alembic commands ###
