"""add-blend-users-to-recommendation

Revision ID: a2dfc8f0e0e3
Revises: e67f76cf8598
Create Date: 2026-06-13 21:42:15.227810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2dfc8f0e0e3"
down_revision: Union[str, Sequence[str], None] = "e67f76cf8598"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recommendation", sa.Column("blend_users", sa.JSON(), nullable=True))
    op.add_column(
        "recommendationsession", sa.Column("blend_users", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendationsession", "blend_users")
    op.drop_column("recommendation", "blend_users")
    # ### end Alembic commands ###
