"""initialise-models

Revision ID: bfc623fba7b7
Revises: 
Create Date: 2026-06-09 17:21:42.176483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfc623fba7b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloadsession',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('track_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('status', sa.Enum('pending', 'downloading', 'completed', 'failed', name='downloadsessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloadsession_status'), 'downloadsession', ['status'], unique=False)
    op.create_table('notification',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('discord', name='notificationchannel'), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_table('recommendation',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('strategy', sa.Enum('top_tracks', 'recent_tracks', 'mixed', name='recommendationstrategy'), nullable=False),
    sa.Column('lastfm_username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_username'), 'recommendation', ['username'], unique=True)
    op.create_table('recommendationsession',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider', sa.Enum('lastfm', name='recommendationprovider'), nullable=False),
    sa.Column('strategy', sa.Enum('top_tracks', 'recent_tracks', 'mixed', name='recommendationstrategy'), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='recommendationstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendationsession_provider'), 'recommendationsession', ['provider'], unique=False)
    op.create_index(op.f('ix_recommendationsession_username'), 'recommendationsession', ['username'], unique=False)
    op.create_table('sync',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('spotify', 'youtube', name='syncprovider'), nullable=False),
    sa.Column('playlist_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('playlist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('enable_sync', sa.Boolean(), nullable=False),
    sa.Column('enable_download', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_playlist_id'), 'sync', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_sync_provider'), 'sync', ['provider'], unique=False)
    op.create_index(op.f('ix_sync_username'), 'sync', ['username'], unique=False)
    op.create_table('syncsession',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('spotify', 'youtube', name='syncprovider'), nullable=False),
    sa.Column('provider_playlist_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider_playlist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('target_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_playlist_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_playlist_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='syncstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncsession_provider'), 'syncsession', ['provider'], unique=False)
    op.create_index(op.f('ix_syncsession_provider_playlist_id'), 'syncsession', ['provider_playlist_id'], unique=False)
    op.create_index(op.f('ix_syncsession_target_playlist_id'), 'syncsession', ['target_playlist_id'], unique=False)
    op.create_index(op.f('ix_syncsession_target_user_id'), 'syncsession', ['target_user_id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_id'), 'user', ['oauth_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('recommendationsessiontrack',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('type', sa.Enum('total', 'matched', 'missing', 'downloaded', name='recommendationtracktype'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_session_id'], ['recommendationsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendationsessiontrack_recommendation_session_id'), 'recommendationsessiontrack', ['recommendation_session_id'], unique=False)
    op.create_table('syncsessiontrack',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sync_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('type', sa.Enum('total', 'new', 'outdated', 'missing', 'downloaded', name='syncsessiontracktype'), nullable=False),
    sa.ForeignKeyConstraint(['sync_session_id'], ['syncsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncsessiontrack_sync_session_id'), 'syncsessiontrack', ['sync_session_id'], unique=False)
    op.create_index(op.f('ix_syncsessiontrack_type'), 'syncsessiontrack', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncsessiontrack_type'), table_name='syncsessiontrack')
    op.drop_index(op.f('ix_syncsessiontrack_sync_session_id'), table_name='syncsessiontrack')
    op.drop_table('syncsessiontrack')
    op.drop_index(op.f('ix_recommendationsessiontrack_recommendation_session_id'), table_name='recommendationsessiontrack')
    op.drop_table('recommendationsessiontrack')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_syncsession_target_user_id'), table_name='syncsession')
    op.drop_index(op.f('ix_syncsession_target_playlist_id'), table_name='syncsession')
    op.drop_index(op.f('ix_syncsession_provider_playlist_id'), table_name='syncsession')
    op.drop_index(op.f('ix_syncsession_provider'), table_name='syncsession')
    op.drop_table('syncsession')
    op.drop_index(op.f('ix_sync_username'), table_name='sync')
    op.drop_index(op.f('ix_sync_provider'), table_name='sync')
    op.drop_index(op.f('ix_sync_playlist_id'), table_name='sync')
    op.drop_table('sync')
    op.drop_index(op.f('ix_recommendationsession_username'), table_name='recommendationsession')
    op.drop_index(op.f('ix_recommendationsession_provider'), table_name='recommendationsession')
    op.drop_table('recommendationsession')
    op.drop_index(op.f('ix_recommendation_username'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_table('notification')
    op.drop_index(op.f('ix_downloadsession_status'), table_name='downloadsession')
    op.drop_table('downloadsession')
    # ### end Alembic commands ###
