"""create-library-track-model

Revision ID: d5d3f1720561
Revises: 7e79d4942139
Create Date: 2026-09-02 12:40:00.463783

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5d3f1720561'
down_revision: str | Sequence[str] | None = '7e79d4942139'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraryfolder',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraryfolder_path'), 'libraryfolder', ['path'], unique=True)
    op.create_table('librarytrack',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('directory', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('album', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('musicbrainz_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('has_lyrics', sa.Boolean(), nullable=False),
    sa.Column('is_synced_lyrics', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_librarytrack_directory'), 'librarytrack', ['directory'], unique=False)
    op.create_index(op.f('ix_librarytrack_format'), 'librarytrack', ['format'], unique=False)
    op.create_index(op.f('ix_librarytrack_has_lyrics'), 'librarytrack', ['has_lyrics'], unique=False)
    op.create_index(op.f('ix_librarytrack_path'), 'librarytrack', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_librarytrack_path'), table_name='librarytrack')
    op.drop_index(op.f('ix_librarytrack_has_lyrics'), table_name='librarytrack')
    op.drop_index(op.f('ix_librarytrack_format'), table_name='librarytrack')
    op.drop_index(op.f('ix_librarytrack_directory'), table_name='librarytrack')
    op.drop_table('librarytrack')
    op.drop_index(op.f('ix_libraryfolder_path'), table_name='libraryfolder')
    op.drop_table('libraryfolder')
    # ### end Alembic commands ###
