"""add-playlist-name-to-recommendation

Revision ID: e67f76cf8598
Revises: bfc623fba7b7
Create Date: 2026-06-13 16:06:12.101526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e67f76cf8598"
down_revision: Union[str, Sequence[str], None] = "bfc623fba7b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recommendation",
        sa.Column(
            "playlist_name",
            sqlmodel.sql.sqltypes.AutoString(length=256),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendation", "playlist_name")
    # ### end Alembic commands ###
