"""add-cron-expression-to-recommendation

Revision ID: e99666fd428a
Revises: fe8221cd4d6f
Create Date: 2026-05-17 22:06:56.893463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e99666fd428a"
down_revision: Union[str, Sequence[str], None] = "fe8221cd4d6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recommendation",
        sa.Column(
            "cron_expression",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendation", "cron_expression")
    # ### end Alembic commands ###
