"""create-recommendation-setting-model

Revision ID: f2337988e394
Revises: d09e406a2f04
Create Date: 2026-04-22 20:28:55.365927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2337988e394'
down_revision: Union[str, Sequence[str], None] = 'd09e406a2f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendationsetting',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('strategy', sa.Enum('top_tracks', 'recent_tracks', name='recommendationstrategy'), nullable=False),
    sa.Column('lastfm_username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendationsetting_username'), 'recommendationsetting', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendationsetting_username'), table_name='recommendationsetting')
    op.drop_table('recommendationsetting')
    # ### end Alembic commands ###
