"""add-is-admin-to-user

Revision ID: fe8221cd4d6f
Revises: 3156ac7e280d
Create Date: 2026-05-17 11:50:28.611035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe8221cd4d6f"
down_revision: Union[str, Sequence[str], None] = "3156ac7e280d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            'UPDATE "user" '
            "SET is_admin = true "
            "WHERE id IN ("
            'SELECT id FROM "user" ORDER BY created_at ASC, id ASC LIMIT 1'
            ")"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
