name: Build

on:
  workflow_call:

env:
  WEB_IMAGE: ghcr.io/${{ github.repository }}/web
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend

jobs:
  build-web:
    name: Build Web
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build web Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          target: runner
          push: false
          tags: ${{ env.WEB_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
