name: Build, Lint, and Test Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    needs: [lint, test]
    uses: ./.github/workflows/build.yml
