name: Build and Lint Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build:
    name: Build
    needs: lint
    uses: ./.github/workflows/build.yml
